# Generated by Django 3.2.9 on 2022-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1500)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
