# Generated by Django 3.2.9 on 2021-12-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211208_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
