# Generated by Django 3.2.9 on 2021-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_project_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='framed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='friendly_name',
            field=models.CharField(max_length=254),
        ),
    ]
